name: build-amx

on:
  workflow_dispatch:
  push:
    paths:
      - "NoPixelMode.pwn"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake ninja-build clang curl

      - name: Get pawn compiler
        run: |
          git clone --depth 1 https://github.com/pawn-lang/compiler.git compiler
          cmake -S compiler/source/compiler -B compiler/build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build compiler/build -j2
          # show where pawncc ended up (path varies)
          find compiler/build -type f -name pawncc -perm -111 -print

      - name: Get SA:MP includes
        run: |
          git clone --depth 1 https://github.com/pawn-lang/samp-stdlib.git
          mkdir -p includes
          cp samp-stdlib/*.inc includes/

      - name: Compile gamemode
        run: |
          PAWNCC=$(find compiler/build -type f -name pawncc -perm -111 | head -n1)
          echo "Using pawncc at: $PAWNCC"
          $PAWNCC NoPixelMode.pwn -i includes -o NoPixelMode.amx -O1 -d0 -e build_errors.txt || true
          if [ -s build_errors.txt ]; then
            echo "Compiler output:"; cat build_errors.txt; exit 1
          fi
          ls -l NoPixelMode.amx

      - name: Upload AMX artifact
        uses: actions/upload-artifact@v4
        with:
          name: NoPixelMode-amx
          path: NoPixelMode.amx
