name: build-amx

on:
  workflow_dispatch:
  push:
    paths:
      - "NoPixelMode.pwn"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git tar

      - name: Download Pawn compiler (v3.10.10)
        run: |
          set -e
          curl -L "https://github.com/pawn-lang/compiler/releases/download/v3.10.10/pawnc-3.10.10-linux.tar.gz" -o pawnc.tar.gz
          mkdir -p $HOME/pawnc
          tar -xzf pawnc.tar.gz -C $HOME/pawnc
          echo "$HOME/pawnc/pawnc-3.10.10-linux" >> $GITHUB_PATH
          ls -l $HOME/pawnc/pawnc-3.10.10-linux

      - name: Get SA:MP includes
        run: |
          set -e
          git clone https://github.com/pawn-lang/samp-stdlib.git
          mkdir -p includes
          cp samp-stdlib/*.inc includes/
          ls -l includes

      - name: Compile gamemode
        run: |
          set -e
          pawncc NoPixelMode.pwn -i includes -o NoPixelMode.amx -O1 -d0 -Z -e build_errors.txt || true
          if [ ! -f NoPixelMode.amx ]; then
            echo "Build failed. Showing errors:"
            [ -s build_errors.txt ] && sed -n '1,2000p' build_errors.txt
            exit 1
          fi
          ls -l NoPixelMode.amx

      - name: Upload AMX artifact
        uses: actions/upload-artifact@v4
        with:
          name: NoPixelMode-amx
          path: NoPixelMode.amx
