name: build-amx
on:
  workflow_dispatch:
  push:
    paths:
      - "NoPixelMode.pwn"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git

      - name: Download Pawn compiler (v3.10.10)
        run: |
          mkdir -p pawnc
          curl -L https://github.com/pawn-lang/compiler/releases/download/v3.10.10/pawnc-3.10.10-linux.tar.gz -o pawnc.tar.gz
          tar -xzf pawnc.tar.gz -C pawnc --strip-components=1
          chmod +x pawnc/pawncc
          echo "$(pwd)/pawnc" >> $GITHUB_PATH

      - name: Get SA:MP includes
        run: |
          git clone https://github.com/pawn-lang/samp-stdlib.git
          mkdir -p includes
          cp samp-stdlib/*.inc includes/

      - name: Compile gamemode
        run: |
          pawnc/pawncc NoPixelMode.pwn -i includes -o NoPixelMode.amx -O1 -d0 -Z \
          || (echo "Compiler output:" && cat NoPixelMode.lst && exit 1)

      - name: Upload AMX artifact
        uses: actions/upload-artifact@v4
        with:
          name: NoPixelMode-amx
          path: NoPixelMode.amx
